---


- name: register whether we are also a logged-in console user
  shell: /usr/bin/stat -f "%Su" /dev/console
  register: terminal_console_user
  changed_when: False
  become: false
 
- debug: var=terminal_console_user.stdout
  become: false

- debug: var=ansible_user_id

- name: register the current terminal profile
  shell: defaults read "com.apple.Terminal" "Default Window Settings"
  register: terminal_profile_result
  changed_when: False

- name: store the terminal profile in /tmp
  copy:
    src: "base16-eighties.dark.256.terminal"
    dest: "/tmp/base16-eighties.dark.256.terminal"
  when: terminal_profile_result.stdout != "base16-eighties.dark.256"

- name: install the terminal profile
  shell: open /tmp/base16-eighties.dark.256.terminal
  when: terminal_profile_result.stdout != "base16-eighties.dark.256" and terminal_console_user.stdout != ansible_user_id

- name: set the Default Window Settings
  osx_defaults:
    domain: com.apple.Terminal
    key: Default Window Settings
    type: string
    value: "base16-eighties.dark.256"
    state: present

- name: set the Startup Window Settings
  osx_defaults:
    domain: com.apple.Terminal
    key: Startup Window Settings
    type: string
    value: "base16-eighties.dark.256"
    state: present
